name: web

on: 
  push:
    paths:
      - 'web-demo/**'

jobs:
  terraform:
    runs-on: self-hosted

    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      WORKING_DIR: ./web-demo

    steps:
      - uses: actions/checkout@v3

      - name: 'Get last commit message'
        id: get_commit_message
        run: |
          # Attempt to get the last commit message and store it in the environment variable
          COMMIT_MSG=$(git log -n 1 --pretty=format:'%s')
          
          # Check if the commit message is empty and set a default if it is
          if [ -z "$COMMIT_MSG" ]; then
            echo "COMMIT_MESSAGE=No commit message found" >> $GITHUB_ENV
          else
            echo "COMMIT_MESSAGE=$COMMIT_MSG" >> $GITHUB_ENV
          fi

          # List recent commits for debugging
          git log --oneline

      - name: 'Terraform init'
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Conditionally run terraform action'
        shell: pwsh  # Ensures the use of PowerShell
        run: |
          # Print the environment variable for debugging
          Write-Host "Commit Message from ENV: $env:COMMIT_MESSAGE"

          # Retrieve the commit message from environment variable and trim whitespace
          $commitMessage = $env:COMMIT_MESSAGE.Trim()  # Trim whitespace

          # Output the commit message for debugging
          Write-Host "Commit Message: '$commitMessage'"

          # Check if the commit message contains "destroy"
          if ($commitMessage -like "*destroy*") {
            Write-Host "Executing terraform destroy..."
            terraform destroy -auto-approve
          } else {
            Write-Host "Executing terraform apply..."
            terraform apply -auto-approve
          }
        working-directory: ${{ env.WORKING_DIR }}
