name: web

on: 
  push:
    paths:
      - 'web-demo/**'

jobs:
  terraform:
    runs-on: self-hosted

    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      WORKING_DIR: ./web-demo  # Ensure this path is accessible in Bash

    steps:
      - uses: actions/checkout@v3

      - name: 'Get last commit message'
        id: get_commit_message
        shell: bash  # Specify Bash as the shell
        run: |
          # Get the last commit message and set it as an environment variable
          COMMIT_MESSAGE=$(git log -n 1 --pretty=format:'%s')
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "Last commit message: '$COMMIT_MESSAGE'"  # Print for debugging

      - name: 'Terraform init'
        id: init
        shell: bash  # Use Bash
        run: terraform init
        working-directory: "${{ github.workspace }}/${{ env.WORKING_DIR }}"  # Correctly reference working directory

      - name: 'Terraform plan'
        id: plan
        shell: bash  # Use Bash
        run: terraform plan
        working-directory: "${{ github.workspace }}/${{ env.WORKING_DIR }}"  # Correctly reference working directory

      - name: 'Conditionally run terraform action'
        shell: bash  # Use Bash
        run: |
          # Retrieve the commit message from the environment variable
          commitMessage=$COMMIT_MESSAGE

          # Print the commit message for debugging
          echo "Commit Message: '$commitMessage'"

          # Check if the commit message contains "destroy"
          if [[ "$commitMessage" == *"destroy"* ]]; then
            echo "Executing terraform destroy..."
            terraform destroy -auto-approve
          else
            echo "Executing terraform apply..."
            terraform apply -auto-approve
          fi
        working-directory: "${{ github.workspace }}/${{ env.WORKING_DIR }}"  # Correctly reference working directory
