name: web

on: 
  push:
    paths:
      - '/web-demo/**'

  workflow_dispatch:
      
      
jobs:
  resourcegroups:
    runs-on: ubuntu_latest

    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLEINT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      WORKING_DIR: ./web-demo

    steps:
        - uses: actions/checkout@v3

        - name: 'Terraform init'
          id: init
          run: terraform init
          working-directory: ${{ env.WORKING_DIR }}

          
        - name: 'Terraform plan'
          id: plan
          run: terraform plan
          working-directory: ${{ env.WORKING_DIR }}

          
        - name: 'Terraform apply'
          id: apply
          run: terraform apply
          working-directory: ${{ env.WORKING_DIR }}
